/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandMark: typeof import('./src/components/BrandMark.vue')['default']
    ConnectionTile: typeof import('./src/components/ConnectionTile.vue')['default']
    DiscordSpecimen: typeof import('./src/components/DiscordSpecimen.vue')['default']
    DrawnCheck: typeof import('./src/components/setup/DrawnCheck.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedIndicator: typeof import('./src/components/settings/SavedIndicator.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
