<!--
  -- This vue generated by google in response to query:
  -- "vue component that applies all parameters to a div"
  -- Adapted for <a> - Seems to work great!
  --
  -- Using:
  -- Use like a normal <a> tag:
  --    <URL href="https://www.google.com">Click Me!</URL>
  -->
<script setup>
import {BrowserOpenURL} from "../../wailsjs/runtime";

function openUrl(event) {
    event.preventDefault();
    // Defer to wails - Opens the given URL in the system browser.
    BrowserOpenURL(event.currentTarget.href);
}
</script>

<template>
    <a v-bind="$attrs" @click="openUrl($event)"><slot/></a>
</template>

<script>
export default {
    inheritAttrs: false,
};
</script>
