/**
 * Changelog / release-notes parsing.
 *
 * GitHub release bodies for PlexCord are generated by semantic-release
 * (conventional-changelog), so they arrive as Markdown, e.g.:
 *
 *   ## [1.7.1](https://github.com/…/compare/v1.7.0…v1.7.1) (2026-07-10)
 *
 *   ### Bug Fixes
 *
 *   * **brand:** replace placeholder W icon with logo ([#64](url)) ([abc1234](url))
 *
 * Rendering that raw string in the About panel leaks Markdown syntax and
 * commit/PR reference links into the UI. These helpers strip the Markdown
 * down to readable plain text and group it into titled sections so the
 * update row can present a clean preview.
 */

/**
 * Strip inline Markdown from a single line of text.
 *
 * Removes trailing conventional-changelog reference links — `([#64](url))`
 * and `([abc1234](url))` — then collapses any remaining `[text](url)` links
 * to their text and drops bold/italic/inline-code markers. A dangling
 * reference fragment (left behind when the backend truncates the body
 * mid-link) is also trimmed.
 *
 * @param {string} text
 * @returns {string}
 */
export function stripInlineMarkdown(text) {
    let s = String(text ?? '');
    // Drop a dangling, truncation-clipped reference fragment at the end.
    s = s.replace(/\s*\(\[[^)]*$/, '');
    // Drop complete trailing reference links: ([#64](url)) ([abc1234](url)).
    s = s.replace(/\s*\(\[[^\]]+\]\([^)]*\)\)/g, '');
    // Collapse remaining Markdown links [text](url) -> text.
    s = s.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1');
    // Bold, italic, inline code.
    s = s.replace(/\*\*([^*]+)\*\*/g, '$1');
    s = s.replace(/\*([^*]+)\*/g, '$1');
    s = s.replace(/`([^`]+)`/g, '$1');
    return s.replace(/\s+/g, ' ').trim();
}

/**
 * Parse a Markdown release body into titled sections.
 *
 * Level 1–2 headings (the version header semantic-release emits) are
 * dropped because the version is already shown alongside the notes. Level
 * 3+ headings (`### Bug Fixes`, `### Features`, …) become section titles,
 * and `*`/`-` bullets become that section's items. Bullets or paragraphs
 * that appear before any heading collect into a leading untitled section.
 *
 * @param {string} markdown - Raw release-notes Markdown.
 * @returns {Array<{ title: string, items: string[] }>} Sections with at
 *   least one item; empty when there is nothing to show.
 */
export function parseReleaseNotes(markdown) {
    const sections = [];
    let current = null;

    const ensureSection = () => {
        if (!current) {
            current = { title: '', items: [] };
            sections.push(current);
        }
        return current;
    };

    for (const raw of String(markdown ?? '').split(/\r?\n/)) {
        const line = raw.trim();
        if (!line) continue;

        const heading = line.match(/^(#{1,6})\s+(.*)$/);
        if (heading) {
            // Skip the version header (level 1–2); start a section otherwise.
            if (heading[1].length >= 3) {
                current = { title: stripInlineMarkdown(heading[2]), items: [] };
                sections.push(current);
            }
            continue;
        }

        const bullet = line.match(/^[*+-]\s+(.*)$/);
        const text = stripInlineMarkdown(bullet ? bullet[1] : line);
        if (text) {
            ensureSection().items.push(text);
        }
    }

    return sections.filter((section) => section.items.length > 0);
}

/**
 * Render a release body as a compact, single-line plain-text summary.
 *
 * Useful as a fallback where a structured list does not fit. Joins section
 * items with separators and truncates on a word boundary.
 *
 * @param {string} markdown
 * @param {number} [maxLen=120]
 * @returns {string}
 */
export function summarizeReleaseNotes(markdown, maxLen = 120) {
    const items = parseReleaseNotes(markdown).flatMap((section) => section.items);
    const summary = items.join(' • ');
    if (summary.length <= maxLen) {
        return summary;
    }
    const clipped = summary.slice(0, maxLen);
    const lastSpace = clipped.lastIndexOf(' ');
    return `${(lastSpace > 0 ? clipped.slice(0, lastSpace) : clipped).trimEnd()}…`;
}
