// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {version} from '../models';
import {plex} from '../models';
import {main} from '../models';
import {retry} from '../models';
import {errors} from '../models';
import {config} from '../models';

export function AddServer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CheckForUpdate():Promise<version.UpdateInfo>;

export function CheckPlexPINAuth(arg1:number):Promise<Record<string, any>>;

export function CheckSetupComplete():Promise<boolean>;

export function ClearDiscordPresence():Promise<void>;

export function CompleteSetup():Promise<void>;

export function ConnectDiscord(arg1:string):Promise<void>;

export function DisconnectDiscord():Promise<void>;

export function DiscoverPlexServers():Promise<Array<plex.Server>>;

export function GetAutoStart():Promise<boolean>;

export function GetConnectionHistory():Promise<main.ConnectionHistory>;

export function GetCurrentSession():Promise<plex.MusicSession>;

export function GetDefaultDiscordClientID():Promise<string>;

export function GetDiscordClientID():Promise<string>;

export function GetDiscordRetryState():Promise<retry.RetryState>;

export function GetErrorInfo(arg1:string):Promise<errors.ErrorInfo>;

export function GetHideWhenPaused():Promise<Record<string, any>>;

export function GetPresenceFormat():Promise<main.PresenceFormatSettings>;

export function IsPresencePaused():Promise<boolean>;

export function GetMinimizeToTray():Promise<boolean>;

export function GetPlexConnectionStatus():Promise<main.PlexConnectionStatus>;

export function GetPlexRetryState():Promise<retry.RetryState>;

export function GetPlexToken():Promise<string>;

export function GetPlexUsers(arg1:string):Promise<Array<plex.PlexUser>>;

export function GetServers():Promise<Array<config.ServerConfig>>;

export function GetPollingInterval():Promise<number>;

export function GetResourceStats():Promise<main.ResourceStats>;

export function GetVersion():Promise<version.Info>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function IsAuthError(arg1:string):Promise<boolean>;

export function IsDiscordConnected():Promise<boolean>;

export function IsPollingActive():Promise<boolean>;

export function IsRetryableError(arg1:string):Promise<boolean>;

export function MinimizeWindow():Promise<void>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function OpenReleasesPage():Promise<void>;

export function QuitApp():Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;

export function ResetApplication():Promise<void>;

export function RetryDiscordConnection():Promise<void>;

export function RetryPlexConnection():Promise<void>;

export function SaveDiscordClientID(arg1:string):Promise<void>;

export function SavePlexToken(arg1:string):Promise<void>;

export function SavePlexUserSelection(arg1:string,arg2:string):Promise<void>;

export function SaveServerURL(arg1:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetServerActive(arg1:string,arg2:boolean):Promise<void>;

export function SetHideWhenPaused(arg1:boolean,arg2:number):Promise<void>;

export function SetPresenceFormat(arg1:string,arg2:string):Promise<void>;

export function TogglePresencePause():Promise<boolean>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function SetPollingInterval(arg1:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function SkipSetup():Promise<void>;

export function StartPlexPINAuth():Promise<Record<string, any>>;

export function StartSessionPolling():Promise<void>;

export function StopSessionPolling():Promise<void>;

export function TestDiscordPresence():Promise<void>;

export function UpdateDiscordPresence(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<void>;

export function ValidateDiscordClientID(arg1:string):Promise<void>;

export function ValidatePlexConnection(arg1:string):Promise<plex.ValidationResult>;
