// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckPlexPINAuth(arg1) {
  return window['go']['main']['App']['CheckPlexPINAuth'](arg1);
}

export function CheckSetupComplete() {
  return window['go']['main']['App']['CheckSetupComplete']();
}

export function ClearDiscordPresence() {
  return window['go']['main']['App']['ClearDiscordPresence']();
}

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function ConnectDiscord(arg1) {
  return window['go']['main']['App']['ConnectDiscord'](arg1);
}

export function DisconnectDiscord() {
  return window['go']['main']['App']['DisconnectDiscord']();
}

export function DiscoverPlexServers() {
  return window['go']['main']['App']['DiscoverPlexServers']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetConnectionHistory() {
  return window['go']['main']['App']['GetConnectionHistory']();
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetDefaultDiscordClientID() {
  return window['go']['main']['App']['GetDefaultDiscordClientID']();
}

export function GetDiscordClientID() {
  return window['go']['main']['App']['GetDiscordClientID']();
}

export function GetDiscordRetryState() {
  return window['go']['main']['App']['GetDiscordRetryState']();
}

export function GetErrorInfo(arg1) {
  return window['go']['main']['App']['GetErrorInfo'](arg1);
}

export function GetMinimizeToTray() {
  return window['go']['main']['App']['GetMinimizeToTray']();
}

export function GetPlexConnectionStatus() {
  return window['go']['main']['App']['GetPlexConnectionStatus']();
}

export function GetPlexRetryState() {
  return window['go']['main']['App']['GetPlexRetryState']();
}

export function GetPlexToken() {
  return window['go']['main']['App']['GetPlexToken']();
}

export function GetPlexUsers(arg1) {
  return window['go']['main']['App']['GetPlexUsers'](arg1);
}

export function GetPollingInterval() {
  return window['go']['main']['App']['GetPollingInterval']();
}

export function GetResourceStats() {
  return window['go']['main']['App']['GetResourceStats']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsAuthError(arg1) {
  return window['go']['main']['App']['IsAuthError'](arg1);
}

export function IsDiscordConnected() {
  return window['go']['main']['App']['IsDiscordConnected']();
}

export function IsPollingActive() {
  return window['go']['main']['App']['IsPollingActive']();
}

export function IsRetryableError(arg1) {
  return window['go']['main']['App']['IsRetryableError'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenReleaseURL(arg1) {
  return window['go']['main']['App']['OpenReleaseURL'](arg1);
}

export function OpenReleasesPage() {
  return window['go']['main']['App']['OpenReleasesPage']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ResetApplication() {
  return window['go']['main']['App']['ResetApplication']();
}

export function RetryDiscordConnection() {
  return window['go']['main']['App']['RetryDiscordConnection']();
}

export function RetryPlexConnection() {
  return window['go']['main']['App']['RetryPlexConnection']();
}

export function SaveDiscordClientID(arg1) {
  return window['go']['main']['App']['SaveDiscordClientID'](arg1);
}

export function SavePlexToken(arg1) {
  return window['go']['main']['App']['SavePlexToken'](arg1);
}

export function SavePlexUserSelection(arg1, arg2) {
  return window['go']['main']['App']['SavePlexUserSelection'](arg1, arg2);
}

export function SaveServerURL(arg1) {
  return window['go']['main']['App']['SaveServerURL'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['main']['App']['SetMinimizeToTray'](arg1);
}

export function SetPollingInterval(arg1) {
  return window['go']['main']['App']['SetPollingInterval'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SkipSetup() {
  return window['go']['main']['App']['SkipSetup']();
}

export function StartPlexPINAuth() {
  return window['go']['main']['App']['StartPlexPINAuth']();
}

export function StartSessionPolling() {
  return window['go']['main']['App']['StartSessionPolling']();
}

export function StopSessionPolling() {
  return window['go']['main']['App']['StopSessionPolling']();
}

export function TestDiscordPresence() {
  return window['go']['main']['App']['TestDiscordPresence']();
}

export function UpdateDiscordPresence(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateDiscordPresence'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ValidateDiscordClientID(arg1) {
  return window['go']['main']['App']['ValidateDiscordClientID'](arg1);
}

export function ValidatePlexConnection(arg1) {
  return window['go']['main']['App']['ValidatePlexConnection'](arg1);
}
